#!/usr/bin/env bash
# Rejects commit messages containing AI tool or co-author attributions.
# Enforces the same rule as .claude/skills/git-ship/SKILL.md (assertion A2).
set -euo pipefail

msg_file="${1:?commit message file path required}"
msg="$(cat "$msg_file")"

# Strip comment lines (git's default editor adds them) before scanning.
scan="$(printf '%s\n' "$msg" | grep -v '^#' || true)"

forbidden_patterns=(
    'Co-Authored-By:'
    'Co-authored-by:'
    'Generated with'
    'Generated by Claude'
    '🤖'
    'noreply@anthropic.com'
)

for pattern in "${forbidden_patterns[@]}"; do
    if printf '%s' "$scan" | grep -qiF "$pattern"; then
        echo "error: commit message contains forbidden attribution: '$pattern'" >&2
        echo "hint: remove AI/co-author trailers. See .claude/skills/git-ship/SKILL.md A2." >&2
        exit 1
    fi
done
